interface:
  theme: light
  max_results_display: 5
retrieval:
  chunk_size: 1000
  chunk_overlap: 200
  k_retrieval: 3
  embedding_model: all-MiniLM-L6-v2
generation:
  model: mistral
  temperature: 0.7
  max_tokens: 500
  ollama_host: http://localhost:11434
  ollama_port: 11434
system:
  auto_save: true
  log_level: INFO
  cache_embeddings: true
  max_query_history: 10
paths:
  data_dir: data
  models_dir: models
  embeddings_file: models/embeddings.pkl
  faiss_index_file: models/faiss_index.pkl
