interface:
  theme: light
  max_results_display: 5
retrieval:
  chunk_size: 1000
  chunk_overlap: 200
  k_retrieval: 3
  embedding_model: nomic-ai/nomic-embed-text-v1.5
generation:
  model: mistral
  temperature: 0.7
  max_tokens: 500
  ollama_host: http://localhost:11434
  ollama_port: 11434
system:
  auto_save: true
  log_level: INFO
  cache_embeddings: true
  max_query_history: 10
paths:
  data_dir: data
  temp_upload_dir: /tmp/rag_uploads
  # Note: Storage now uses PostgreSQL + Elasticsearch instead of local files
